### ISSUE TITLE
DiscordAPIError: Unknown interaction

### ISSUE THREAD

**Issue by Farhan1003** [WekyDev/weky-npm#54]
When I run commands like calculator, fight, snake, and interact with the buttons this error pops up on the console...

`DiscordAPIError: Unknown interaction
    at RequestHandler.execute (/home/runner/Nodejs14-template/node_modules/discord.js/src/rest/RequestHandler.js:154:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RequestHandler.push (/home/runner/Nodejs14-template/node_modules/discord.js/src/rest/RequestHandler.js:39:14)
    at async InteractionReply.defer (/home/runner/Nodejs14-template/node_modules/discord-buttons/src/v12/Classes/managers/InteractionReply.js:63:5) {
  method: 'post',
  path: '/interactions/889762319339515904/aW50ZXJhY3Rpb246ODg5NzYyMzE5MzM5NTE1OTA0Ok1TelBTOHJ1czBMZE9FcTNrenN3ZzFOalFrWFh3a2Q2VkVXRjNpd1dZM1M0TzZWREh2cE56WWFmeHRzY2VIb2FTbXN1TFZsREZJTE5FbXZtNmNCYzdqWHJRTlNURndSTlR0MU4xNFpQTE9ma1luVEMyM1VMS2tNOHBwVU9kSTJt/callback',
  code: 10062,
  httpStatus: 404
}
` 
The command works but every time someone clicks on those buttons console gets spammed with this. Btw only commands related to Weky aka cal, fight, snake has this error. I have other separate commands that uses the discord-buttons package too but those don't cause any errors.
**My info.**
Node js: 16
Discord.js: 12.5.3
Discord buttons & Weky : Latest version

**Comment by sujalgoel** [comment]
We are removing the support for djsv12 and this most likely occurs due to an error in `discord-buttons` package
